# server port 설정
server:
  port: 8080
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
    whitelabel:
      enabled: false  # 기본 오류 페이지 대신 직접 만든 오류 페이지 사용

# Spring 설정
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 2KB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_board_v2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  security:
    user:
      name: admin
      password: admin
  # SQL 초기화 모드 설정 (이 부분이 로깅 설정 아래에 있어서 문제가 발생함)
  sql:
    init:
      mode: always

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

# 로깅 설정
logging:
  level:
    root: INFO  # 루트 로거 레벨
    com.dukefirstboard.board: DEBUG  # 모든 프로젝트 클래스에 대해 DEBUG 레벨 설정
    com.dukefirstboard.board.controller: DEBUG  # 컨트롤러에서 더 자세한 로깅
    com.dukefirstboard.board.service: DEBUG  # 서비스 레이어에서 더 자세한 로깅
    com.dukefirstboard.board.mapper: DEBUG  # Mapper (SQL) 로깅
    org.springframework.security: DEBUG  # Spring Security 로깅
    org.springframework.web: DEBUG  # Spring Web 로깅
    org.hibernate.SQL: DEBUG  # SQL 쿼리 로깅 (JPA 사용시)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # SQL 파라미터 로깅 (JPA 사용시)
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 콘솔 로그 패턴
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"  # 파일 로그 패턴
  file:
    name: logs/application.log  # 로그 파일 위치

# 파일 업로드 경로 설정 (추가)
file:
  upload-dir: C:/Users/DUKE/Downloads/testsave/